accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accounts.views import custom_login, RegisterView,ProfileView,ProfileListView,ProfileUpdateView,ChangePasswordView,DeleteProfileView,follow_func

app_name = 'accounts'
urlpatterns = [
    path('login/',custom_login,name='login'),
    path('register/',RegisterView.as_view(),name='register'),
    path('logout/',LogoutView.as_view(),name='logout'),


    path('profiles/',ProfileListView.as_view(),name='profiles'),
    path('<int:pk>/profile/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/update/', ProfileUpdateView.as_view(), name='update_profile'),
    path('profile/<int:pk>/change-password/',ChangePasswordView.as_view(), name='change_password'),
    path('profile/<int:pk>/delete/', DeleteProfileView.as_view(), name='delete_profile'),

    path('profile/<int:pk>/follow/',follow_func , name='follow'),
]

instagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views import IndexView, CreatePostView,UpdatePostView,DeletePostView,DetailPostView,AddCommentView,like_post,DeleteCommentView

app_name = 'webapp'
urlpatterns = [
    path('',IndexView.as_view(),name='index'),
    path('create_post/',CreatePostView.as_view(),name='create_post'),
    path('post/<int:pk>/update/',UpdatePostView.as_view(),name='update_post'),
    path('post/<int:pk>/delete/', DeletePostView.as_view(), name='delete_post'),
    path('post/<int:pk>/',DetailPostView.as_view(),name='detail_post'),

    path('post/<int:pk>/add-comment/',AddCommentView.as_view(),name='add_comment'),
    path('comment/<int:pk>/delete/', DeleteCommentView.as_view(), name='delete-comment'),


    path('post/<int:pk>/like/', like_post, name='like_post'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models




class MyUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatars', verbose_name='Аватарка')
    bio = models.TextField(verbose_name='Инфо о пользователе',blank=True,null=True)
    phone_number = models.CharField(verbose_name='Номер телефона',max_length=20,blank=True,null=True)
    gender = models.CharField(choices=[('male','мужчина'),('female','женщина'),('other','остальное')],
                              verbose_name='пол',max_length=10,blank=True,null=True)



class Follow(models.Model):
    follower = models.ForeignKey(MyUser,on_delete=models.CASCADE,related_name='followings',verbose_name='Подписывается')
    following = models.ForeignKey(MyUser,on_delete=models.CASCADE,related_name='followers',verbose_name='На него подписываются')
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='Время подписки')

    def __str__(self):
        return f"{self.follower} на {self.following}"

    class Meta:
        db_table = 'follow'
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import get_user_model, authenticate
from django.db.models import Q
from django.forms import ModelForm

User = get_user_model()

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(label='Логин или Email', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))

    def clean(self):
        username_or_email = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username_or_email and password:
            try:
                user_obj = User.objects.get(Q(username=username_or_email) | Q(email=username_or_email))
                username = user_obj.username
            except User.DoesNotExist:
                username = username_or_email

            self.user_cache = authenticate(self.request, username=username, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    "Неверный логин, email или пароль."
                )
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data


class MyUserCreationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.help_text = None
            field.widget.attrs['class'] = 'form-control'

    avatar = forms.ImageField(required=True,widget=forms.FileInput(),label="Аватар")
    email = forms.EmailField(required=True,widget=forms.EmailInput(),label="Email")
    phone_number = forms.CharField(
        required = False,
        label='Телефон',
        widget=forms.TextInput(attrs={
            'placeholder': '+996 700 000 000',
            'type': 'tel',
        })
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username' , 'email', 'password1', 'password2', 'avatar', 'first_name', 'bio', 'phone_number','gender']


class MyUserChangeForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.help_text = None
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = User
        fields = ['username' , 'email', 'avatar', 'first_name', 'bio', 'phone_number','gender']




class StyledPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='Старый пароль',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
        })
    )
    new_password1 = forms.CharField(
        label='Новый пароль',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
        })
    )
    new_password2 = forms.CharField(
        label='Подтвердите новый пароль',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
        })
    )

accounts/views.py
from urllib.parse import urlencode

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, get_user_model
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from webapp.forms import SearchForm
from webapp.models import LikesModel
from .forms import CustomAuthenticationForm, MyUserCreationForm, MyUserChangeForm, StyledPasswordChangeForm
from .models import Follow

User = get_user_model()

def custom_login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('webapp:index')
    else:
        form = CustomAuthenticationForm()

    return render(request, 'login.html', {'form': form})

class RegisterView(CreateView):
    template_name = 'registration.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())


    def get_success_url(self):
        next = self.request.GET.get('next')
        if not next:
            next = self.request.POST.get('next')
        if not next:
            next = reverse('webapp:index')
        return next


class ProfileView(DetailView):
    model = User
    template_name = 'profile/user_profile.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        posts = self.object.posts.order_by('-id')
        kwargs['posts'] = posts
        if self.request.user.is_authenticated:
            kwargs['is_following'] = self.get_object().followers.filter(follower=self.request.user).exists()
        else:
            kwargs['is_following'] = False
        if self.request.user.is_authenticated:
            likes = LikesModel.objects.filter(user=self.request.user).values_list('post_id', flat=True)
            kwargs['liked_posts'] = likes
        else:
            kwargs['liked_posts'] = []
        return super().get_context_data(**kwargs)


class ProfileListView(ListView):
    model = User
    template_name = 'profile/profile_list.html'
    context_object_name = 'users_obj'

    def dispatch(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']

    def get_queryset(self):
        queryset = super().get_queryset().all()

        if self.search_value:
            queryset = User.objects.filter(
                Q(email__icontains=self.search_value) | Q(
                    username__icontains=self.search_value) | Q(
                    first_name__icontains=self.search_value))
        return queryset

    def get_context_data(self, **kwargs):
        result = super().get_context_data(**kwargs)
        result['search_form'] = self.form
        if self.search_value:
            result['query'] = urlencode({'search': self.search_value})
            result['search'] = self.search_value
        return result


class ProfileUpdateView(PermissionRequiredMixin,UpdateView):
    model = get_user_model()
    form_class = MyUserChangeForm
    template_name = 'profile/update_profile.html'
    context_object_name = 'user_obj'

    def has_permission(self):
        return  self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.object.pk})


class ChangePasswordView(PermissionRequiredMixin,PasswordChangeView):
    template_name = 'profile/change_password.html'
    form_class = StyledPasswordChangeForm

    def has_permission(self):
        user = get_object_or_404(User, pk=self.kwargs['pk'])
        return user == self.request.user

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.request.user.pk})


class DeleteProfileView(PermissionRequiredMixin,DeleteView):
    template_name = 'profile/delete_profile.html'
    model = User
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_user'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object()


@login_required
def follow_func(request,pk):
    if request.method == 'POST':
        follower = request.user
        following = get_object_or_404(User, pk=pk)
        if follower == following:
            return HttpResponseForbidden("Нельзя подписываться на самого себя")
        is_folowed = Follow.objects.filter(follower = follower, following = following).first()

        if is_folowed:
            is_folowed.delete()
        else:
            Follow.objects.create(follower = follower, following = following)

        return redirect('accounts:profile', pk=pk)

accounts/templates/profile/change_password.html
{% extends 'base.html' %}


{% block content %}
    <div class="registration_block mx-auto mt-5 p-4 border rounded w-50">
        <h1 class="text-center">Изменить пароль</h1>
        <form action="" method="post">
            {% include 'partials/form.html' with button_text='Изменить' %}
        </form>
    </div>


{% endblock %}

accounts/templates/profile/delete_profile.html
{% extends 'base.html' %}

{% block  content %}
    <form action="" method="post">
        {% csrf_token %}
        <p class="mt-5">Вы уверены что хотите удалить аккаунт - {{ user.username }} ?</p>
        <a class="btn btn-primary" href="{% url 'webapp:index' %}">Отмена</a>
        <button class="btn btn-danger" type="submit">Да, удалить</button>
    </form>


{% endblock %}

accounts/templates/profile/profile_list.html
{% extends 'base.html' %}

{% block title %}Найти друзей{% endblock %}

{% block content %}
    {% if search %}
        {% if users_obj %}
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4 mt-5">
                {% for user_obj in users_obj %}
                    <div class="col d-flex">
                        <div class="card w-100 d-flex flex-column">
                            {% if user_obj.avatar %}
                                <img src="{{ user_obj.avatar.url }}" class="card-img-top object-fit-cover" style="height: 200px;" alt="Avatar">
                            {% endif %}
                            <div class="card-body d-flex flex-column justify-content-between">
                                <h5 class="card-title mb-3">{{ user_obj.username }}</h5>
                                <a href="{% url 'accounts:profile' user_obj.pk %}" class="btn btn-primary mt-auto w-100">Посетить</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p class="text-center mt-5">Ничего не найдено по запросу.</p>
        {% endif %}
    {% else %}
        <p class="text-center mt-5">Находите друзей</p>
    {% endif %}
{% endblock %}

accounts/templates/profile/update_profile.html
{% extends 'base.html' %}


{% block content %}
    <div class="registration_block mx-auto mt-5 p-4 border rounded w-50">
        <h1 class="text-center">Редактировать профиль</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% include 'partials/form.html' with button_text='Редактировать' %}
        </form>
    </div>


{% endblock %}

accounts/templates/profile/user_profile.html
{% extends 'base.html' %}

{% block nav %}

{% endblock %}

{% block content %}


    <div class="d-flex justify-content-center mt-5">
        <div class="row  align-items-start">
            <div class="col-auto text-center text-md-start mb-3 mb-md-0 me-5">
                {% if user_obj.avatar %}
                    <img src="{{ user_obj.avatar.url }}" alt="Avatar"
                         class="rounded-circle" style="width: 200px; height: 200px; object-fit: cover;">
                {% else %}
                    <img src="https://www.shutterstock.com/image-vector/profile-picture-user-vector-illustration-600nw-2482138073.jpg" class="rounded-circle" style="width: 200px;height: 200px;object-fit: cover" alt="Avatar">
                {% endif %}
            </div>

            <div class="col mt-4">
                <div class="d-flex flex-column flex-sm-row align-items-start align-items-sm-center mb-3 gap-2">
                    <h4 class="mb-0 me-sm-3"><strong>{{ user_obj.username }}</strong></h4>
                    {% if user == user_obj %}
                        <a href="{% url 'accounts:update_profile' user.pk %}" class="btn btn-outline-secondary btn-sm">Редактировать профиль</a>
                        <a href="{% url 'accounts:change_password' user.pk %}" class="btn btn-outline-secondary btn-sm">Сменить пароль</a>
                        <a href="{% url 'accounts:delete_profile' user.pk %}" class="btn btn-outline-danger btn-sm">Удалить аккаунт</a>
                    {% endif %}
                </div>

                <div class="d-flex flex-wrap mb-2 gap-3">
                    <div><strong>{{ user_obj.posts.count }}</strong> публикаций</div>
                    <div><strong>{{ user_obj.followers.count }}</strong> подписчиков</div>
                    <div><strong>{{ user_obj.followings.count }}</strong> Подписки</div>
                </div>

                <div>
                    {% if user_obj.first_name %}
                        <strong>{{ user_obj.first_name }}</strong>
                    {% else %}
                        <strong>{{ user_obj.username }}</strong>
                    {% endif %}
                    <p class="mb-0">{% if user_obj.bio %}{{ user_obj.bio }}{% else %}нет био{% endif %}</p>
                </div>
                {% if user.is_authenticated and user_obj != user%}
                    <div class="mt-4">
                        <form method="post" action="{% url 'accounts:follow' user_obj.pk %}">
                            {% csrf_token %}
                            {% if is_following %}
                                <button type="submit" class="btn btn-danger">Отписаться</button>
                            {% else %}
                                <button type="submit" class="btn btn-primary">Подписаться</button>
                            {% endif %}
                        </form>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 mt-5">
                {% for post in user_obj.posts.all %}
                    <div class="col">
                        {% include 'partials/post_card.html' %}
                    </div>
                        {% empty %}
                            <h5>Пока постов нет</h5>
                {% endfor %}
            </div>
        </div>





{#    <div class="card w-25 mx-auto my-5">#}
{#        {% if user_obj.avatar %}#}
{#            <img src="{{ user_obj.avatar.url }}" class="card-img-top" alt="Avatar">#}
{#        {% endif %}#}
{#        <div class="card-body">#}
{#            <h5 class="card-title">Username: {{ user_obj.username }}</h5>#}
{#            <p class="card-text">#}
{#                {% if user_obj.first_name %}#}
{#                    Имя: {{ user_obj.first_name }}#}
{#                {% endif %}#}
{#            </p>#}
{#            <p class="card-text">#}
{#                <p class="card-text">#}
{#                {% if user_obj.last_name %}#}
{#                    Фамилия: {{ user_obj.last_name }}#}
{#                {% endif %}#}
{#            </p>#}
{#            <p class="card-text">#}
{#            <p class="card-text">#}
{#                {% if user_obj.comments %}#}
{#                    Колличество коментарий: {{ user_obj.comments.count }}#}
{#                {% endif %}#}
{#            </p>#}
{##}
{#        </div>#}
{#    </div>#}
{% endblock %}