accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accounts.views import custom_login, RegisterView,ProfileView,ProfileListView,ProfileUpdateView,ChangePasswordView,DeleteProfileView,follow_func

app_name = 'accounts'
urlpatterns = [
    path('login/',custom_login,name='login'),
    path('register/',RegisterView.as_view(),name='register'),
    path('logout/',LogoutView.as_view(),name='logout'),


    path('profiles/',ProfileListView.as_view(),name='profiles'),
    path('<int:pk>/profile/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/update/', ProfileUpdateView.as_view(), name='update_profile'),
    path('profile/<int:pk>/change-password/',ChangePasswordView.as_view(), name='change_password'),
    path('profile/<int:pk>/delete/', DeleteProfileView.as_view(), name='delete_profile'),

    path('profile/<int:pk>/follow/',follow_func , name='follow'),
]

instagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views import IndexView, CreatePostView,UpdatePostView,DeletePostView,DetailPostView,AddCommentView,like_post,DeleteCommentView

app_name = 'webapp'
urlpatterns = [
    path('',IndexView.as_view(),name='index'),
    path('create_post/',CreatePostView.as_view(),name='create_post'),
    path('post/<int:pk>/update/',UpdatePostView.as_view(),name='update_post'),
    path('post/<int:pk>/delete/', DeletePostView.as_view(), name='delete_post'),
    path('post/<int:pk>/',DetailPostView.as_view(),name='detail_post'),

    path('post/<int:pk>/add-comment/',AddCommentView.as_view(),name='add_comment'),
    path('comment/<int:pk>/delete/', DeleteCommentView.as_view(), name='delete-comment'),


    path('post/<int:pk>/like/', like_post, name='like_post'),
]

webapp/models/comment.py
from django.contrib.auth import get_user_model
from django.db import models


class Comment(models.Model):
   post = models.ForeignKey('webapp.PostModel', related_name='comments', on_delete=models.CASCADE, verbose_name='Пост')
   text = models.TextField(max_length=400, verbose_name='Комментарий')
   author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1, verbose_name='Автор',
                              related_name='comments')
   created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
   updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')


   def __str__(self):
       return self.text[:20]

   class Meta:
       db_table = 'comments'
       verbose_name = 'Коментарий'
       verbose_name_plural = "Коментарий"

webapp/models/post.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone


class PostModel(models.Model):
    image = models.ImageField(upload_to='posts/',verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT,default=1,verbose_name='Автор',related_name='posts')


    def __str__(self):
        return self.description[:10]

    class Meta:
        db_table = 'post'
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'



class LikesModel(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='likes',
        verbose_name='Тот кто лайкнул'
    )
    post = models.ForeignKey(
        PostModel,
        on_delete=models.CASCADE,
        related_name='likes',
        verbose_name='Пост'
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата лайка')

    class Meta:
        unique_together = ('user', 'post')
        db_table = 'like'
        verbose_name = 'Лайк'
        verbose_name_plural = 'Лайки'

    def __str__(self):
        return f"{self.user} нравится {self.post}"

webapp/forms/comment.py
from django import forms

from webapp.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.TextInput(attrs={
                'class': 'form-control me-2 rounded-pill',
                'placeholder': 'Добавить комментарий...',
                'maxlength': 200,
            }),
        }

webapp/forms/post.py
from django import forms

from webapp.models import PostModel


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            if not isinstance(field.widget, forms.CheckboxSelectMultiple):
                field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = PostModel
        fields = ['image','description']

webapp/forms/search.py
from django import  forms

class SearchForm(forms.Form):
    search = forms.CharField(max_length=100,label='Поиск',
                             required=False,
                             widget=forms.TextInput(attrs={'class':'form-control search-input',
                                                           'placeholder':'🔍 Поиск',
                                                           'aria-label':'Поиск','type':'search'}))

webapp/views/comment.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, DeleteView

from webapp.forms import CommentForm
from webapp.models import PostModel, Comment


class AddCommentView(LoginRequiredMixin,CreateView):
    form_class = CommentForm

    def form_valid(self, form):
        post = get_object_or_404(PostModel, pk=self.kwargs['pk'])
        form.instance.post = post
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return  reverse('webapp:detail_post', kwargs={'pk': self.kwargs['pk']})


class DeleteCommentView(PermissionRequiredMixin,DeleteView):
    model = Comment
    permission_required = 'webapp.delete_comment'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().author

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:detail_post', kwargs={'pk': self.object.post.pk})

webapp/views/post.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView

from accounts.models import Follow
from webapp.forms import PostForm, CommentForm
from webapp.models import PostModel, LikesModel


class IndexView(ListView):
    model = PostModel
    template_name = 'post/index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return PostModel.objects.none()
        following_users = Follow.objects.filter(follower=self.request.user).values_list('following', flat=True)
        return PostModel.objects.filter(author__in=following_users).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            likes = LikesModel.objects.filter(user=self.request.user).values_list('post_id', flat=True)
            context['liked_posts'] = likes
        else:
            context['liked_posts'] = []
        return context

class CreatePostView(LoginRequiredMixin,CreateView):
    form_class = PostForm
    template_name = 'post/create_post.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:index')


class UpdatePostView(PermissionRequiredMixin,UpdateView):
    template_name = 'post/update_post.html'
    permission_required = 'webapp.change_post'
    form_class = PostForm
    model = PostModel

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().author

    def get_success_url(self):
        return reverse('webapp:index')


class DeletePostView(PermissionRequiredMixin,DeleteView):
    template_name = 'post/delete_post.html'
    model = PostModel
    success_url = reverse_lazy('webapp:index')

    permission_required = 'webapp.delete_post'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().author


class DetailPostView(DetailView):
    template_name = 'post/detail_post.html'
    model = PostModel
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        result = super().get_context_data(**kwargs)
        result['comments'] = self.object.comments.order_by('created_at')
        result['form'] = CommentForm()
        if self.request.user.is_authenticated:
            likes = LikesModel.objects.filter(user=self.request.user).values_list('post_id', flat=True)
            result['liked_posts'] = likes
        else:
            result['liked_posts'] = []
        return result


@login_required
def like_post(request, pk):
    if request.method == 'POST':
        user = request.user
        post = get_object_or_404(PostModel, pk=pk)
        is_liked = LikesModel.objects.filter(user=user, post=post).first()
        if is_liked:
            is_liked.delete()
        else:
            LikesModel.objects.create(user=user, post=post)
        return redirect(request.META.get('HTTP_REFERER', '/'))

webapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

 <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container">
      <a class="navbar-brand d-flex align-items-center" href="{% url 'webapp:index' %}">
        <img style="height: 35px;margin-right: 6px" src="https://upload.wikimedia.org/wikipedia/commons/a/a5/Instagram_icon.png" alt="Logo">
        <span>Instagram</span>
      </a>

      {% if request.path == '/accounts/profiles/' %}
          <form style="width: 350px" class="d-flex mx-auto">
            {{ search_form.search }}
          </form>
      {% endif %}

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 d-flex flex-row align-items-center">
        {% if request.path != '/accounts/profiles/' %}
            <li class="nav-item mx-3">
              <a class="nav-link" href="{% url 'accounts:profiles' %}">
                    <i class="bi bi-search fs-3"></i>
              </a>
            </li>
         {% endif %}
          {% if user.is_authenticated %}
                <li class="nav-item mx-3">
                  <a class="nav-link" href="{% url 'webapp:create_post' %}">
                    <i class="bi bi-plus-square nav-icon fs-3"></i>
                  </a>
                </li>
                <li class="nav-item mx-3">
                  <a class="nav-link" href="{% url 'accounts:profile' user.pk %}">
                    <i class="bi bi-person nav-icon fs-3"></i>
                  </a>
                </li>
                  <li class="nav-item mx-3">
                      <form action="{% url 'accounts:logout' %}?next={{ request.get_full_path }}" method="post"
                            class="d-inline">
                          {% csrf_token %}
                          <button type="submit" class="btn btn-link p-0 border-0 text-danger" title="Выйти">
                              <i class="bi bi-box-arrow-right fs-3"></i>
                          </button>
                      </form>
                  </li>
          {% else %}
              <li class="nav-item mx-3">
                  <a class="nav-link" href="{% url 'accounts:login' %}?next={{ request.get_full_path }}" title="Войти">
                       <i class="bi bi-box-arrow-in-right fs-3"></i>
                  </a>
              </li>
               <li class="nav-item mx-3">
                  <a class="nav-link" href="{% url 'accounts:register' %}?next={{ request.get_full_path }}" title="Зарегестрироваться">
                       <i class="bi bi-person-plus fs-3"></i>
                  </a>
              </li>
          {% endif %}

      </ul>
    </div>
  </nav>

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>